FROM jupyter/datascience-notebook:latest
COPY xgboost-0.90-py2.py3-none-manylinux1_x86_64.whl .
RUN pip install xgboost-0.90-py2.py3-none-manylinux1_x86_64.whl 
# https://files.pythonhosted.org/packages/c1/24/5fe7237b2eca13ee0cfb100bec8c23f4e69ce9df852a64b0493d49dae4e0/xgboost-0.90-py2.py3-none-manylinux1_x86_64.whl
